api_endpoints:
  - url: "https://httpbin.org/status/200"
    method: "GET"
  - url: "https://httpbin.org/post"
    method: "POST"
    body: '{"test": "data"}'

auth:
  username: "testuser"
  password: "testpass"

injection_payloads:
  - "' OR '1'='1"
  - "'; DROP TABLE users;--"

xss_payloads:
  - "<script>alert('XSS')</script>"
  - "'><script>alert('XSS')</script>"
  - "<img src=x onerror=alert('XSS')>"
  - "javascript:alert('XSS')"

headers:
  "User-Agent": "API-Security-Scanner/1.0"
  "X-Scanner": "true"

rate_limiting:
  requests_per_second: 5
  max_concurrent_requests: 3