version: '3.8'

services:
  # Vulnerable test API - OWASP Juice Shop
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/rest/admin/application-version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # API Security Scanner
  api-security-scanner:
    build: .
    container_name: api-security-scanner
    depends_on:
      juice-shop:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./config-test.yaml:/app/config.yaml
      - ./reports:/app/reports
    environment:
      - SERVER_PORT=8081
      - METRICS_PORT=8080
    command: ["./api-security-scanner", "-config", "config.yaml", "-dashboard"]